### PR TITLE
Bug fixes and code refactoring to get it ready for durable function support

### LINKED ISSUE #71: PSObject returned from function gets in the way of serialization to JSON
Objects returned from function run is warpped into `PSObject`. Further more, the objects in a container object such as array/hastable may also wrapped into `PSObject`. This makes it not possible to directly use `Newtonsoft.Json` in the language worker to serailize object to JSON. We need to consider to use `ConvertTo-Json` for serailizatoin. For deserialization, it should be fine to directly use `Newtonsoft.Json` APIs.

### Repro
**run.ps1**
```powershell
param($req)

Write-Verbose "Processing a HTTP request" -Verbose

$output = @{}
$output["GUID1"] = (New-Guid).Guid
$output["GUID2"] = (New-Guid).Guid

# You associate values to output bindings by calling 'Push-OutputBinding'.
return [HttpResponseContext]@{
    StatusCode = 202
    Body = $output
}
```
**function.json**
```json
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

### Expected Behavior
```
PS> irm http://localhost:7071/api/HttpStartPS
GUID1 GUID2
----- -----
xxxx  XXX
```

### Actual Behavior
```
PS> irm http://localhost:7071/api/HttpStartPS
Microsoft.Azure.Functions.PowerShellWorker.HttpResponseContext
```

### PR DESCRIPTION
**Pull request by daxian-dbw**
Fix #71 

- Use `ConvertTo-Json` for converting the results returned from the function to JSON. So objects that are wrapped in `PSObject` won't be a problem anymore.
- Refactor the code to make it ready for durable function implementation.

The implementation of invoking an orchestration function is made a placeholder in this PR, where it throws `NotImplementedException` when an orchestration function is triggered.
See `RequestProcessor.InvokeOrchestrationFunction`.

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@tylerl0706 I need to work on top of this refactoring for cleaning up the durable function implementation.
Since it's mainly refactoring and CI has passed, I will merge it now. Take your time to review and comment, and I will address your comments in separate PRs.

File: src/Utility/TypeExtensions.cs [hunk 1]
```diff
@@ -129,8 +146,13 @@ static RpcHttp ToRpcHttp (this HttpResponseContext httpResponseContext)
             return rpcHttp;
         }
 
-        public static TypedData ToTypedData(this object value)
+        internal static TypedData ToTypedData(this object value, PowerShellManager psHelper)
```
Comment (tylerl0706) [inline src/Utility/TypeExtensions.cs]: I'm not sure how I feel about having to pass in the psHelper all the time just so that we can reuse the powershell session to run `ConvertTo-Json`... 

Can we just create a constant PowerShell instance in this file that's only used to call `ConvertTo-Json`?
